version: '3.8'

services:
  ebarimt:
    image: munkhaltai/ebarimtgrpc:latest
    restart: always
    platform: linux/amd64
    ports:
      - "8110:8110"
      - "8111:8111"
    volumes:
      - ./vatpsi:/home/ebarimtuser/.vatps
      - ./../pos/pos_api:/home/ebarimtuser/app/sofiles
    environment:
      - TZ=Asia/Ulaanbaatar

